"""Reusable components for the systematic trading research library."""

from .backtest import (
    BacktestResult,
    moving_average_signal,
    run_backtest,
    split_time_series,
    volatility_target_position,
)
from .data import load_price_data, load_price_panel, make_demo_ohlcv
from .portfolio import (
    PortfolioBacktestResult,
    cross_sectional_momentum_weights,
    downside_volatility_momentum_weights,
    dual_momentum_weights,
    equal_weight_weights,
    fifty_two_week_high_weights,
    inverse_volatility_weights,
    low_beta_weights,
    low_volatility_weights,
    minimum_variance_weights,
    momentum_volatility_scaled_weights,
    run_portfolio_backtest,
    short_term_reversal_weights,
    trend_following_rotation_weights,
    time_series_momentum_portfolio_weights,
    volatility_managed_momentum_weights,
    volatility_managed_weights,
    volatility_regime_rotation_weights,
)
from .strategies import (
    bollinger_mean_reversion_signal,
    donchian_breakout_signal,
    time_series_momentum_signal,
)

__all__ = [
    "BacktestResult",
    "load_price_data",
    "load_price_panel",
    "make_demo_ohlcv",
    "moving_average_signal",
    "run_backtest",
    "split_time_series",
    "volatility_target_position",
    "bollinger_mean_reversion_signal",
    "donchian_breakout_signal",
    "time_series_momentum_signal",
    "PortfolioBacktestResult",
    "cross_sectional_momentum_weights",
    "downside_volatility_momentum_weights",
    "dual_momentum_weights",
    "equal_weight_weights",
    "fifty_two_week_high_weights",
    "inverse_volatility_weights",
    "low_beta_weights",
    "low_volatility_weights",
    "minimum_variance_weights",
    "momentum_volatility_scaled_weights",
    "run_portfolio_backtest",
    "short_term_reversal_weights",
    "trend_following_rotation_weights",
    "time_series_momentum_portfolio_weights",
    "volatility_managed_momentum_weights",
    "volatility_managed_weights",
    "volatility_regime_rotation_weights",
]
